-- SQL Dump of JavaDB1.mdb
-- generated by MDB Viewer 2.2.7
-- optimized for MySQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS `student`;

CREATE TABLE `student` (
    `ID` INTEGER PRIMARY KEY,
    `SSN` INTEGER,
    `Name` VARCHAR(50)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `student`(`ID`,`SSN`,`Name`)
VALUES(22,1,'John S.'),
      (23,2,'David T.'),
      (24, 5, 'Cindy W.'),
      (25, 4, 'Monica L');



DROP TABLE IF EXISTS `Students`;

CREATE TABLE `Students` (
    `ID` INTEGER PRIMARY KEY,
    `SSN` INTEGER,
    `Name` VARCHAR(50)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Students`(`ID`,`SSN`,`Name`)
VALUES(22,1,'John S.'),
      (23,2,'David T.'),
      (24, 5, 'Cindy W.'),
      (25, 4, 'Monica L');


